### ISSUE TITLE
Crash on first launch from installer installed app

### ISSUE THREAD

**Issue by JayBeavers** [MSREnable/EyeCatcher#4]
Started app while on a zoom call and the camera was in use and it just crashed to desktop.

App installer is at:

https://s3-us-west-2.amazonaws.com/files.37services.org/index.html

**Comment by JayBeavers** [comment]
May not be due to camera in use.

Need to add crash handling and display error to user.

**Comment by JayBeavers** [comment]
Unhandled exception handler didn't catch and show this.  Instead I had to attach a debugger after launch but before navigate.

System.Exception
  HResult=0x800706D9
  Message=There are no more endpoints available from the endpoint mapper.

There are no more endpoints available from the endpoint mapper.

  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Research.EyeCatcher.Client.PreviewPage.<StartPreviewAsync>d__33.MoveNext() in C:\Data\EyeCatcher\Microsoft.Research.EyeCatcher\Client\PreviewPage.xaml.cs:line 208
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Research.EyeCatcher.Client.PreviewPage.<OnNavigatedTo>d__27.MoveNext() in C:\Data\EyeCatcher\Microsoft.Research.EyeCatcher\Client\PreviewPage.xaml.cs:line 111

**Comment by JayBeavers** [comment]
Found what looks to be a related issue:

https://stackoverflow.com/questions/62622334/no-capture-devices-are-available-in-mediacapture-initializeasync

which implies that Package Manifest -> Capabilities -> Microphone not being selected is the root cause of the weird crash.

**Comment by JayBeavers** [comment]
Confirmed to be an issue with not setting WebCam permissions in the Package Manifest -> Capabilities.
